import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "../globals.css";
import Navbar from "./Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
  
const navLink=[
    {name: "Login", href: "/login"},
    {name: "Register", href: "/register"},
    {name: "forgot passward", href: "/forgot-password"}
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gradient-to-r from-purple-600 via-pink-500 to-red-500">
          <Navbar/>
          {children}
        </div>
      </body>
    </html>
  );
}
